package ecloud.com.model;

import java.util.Date;

import ecloud.com.base.model.BaseModel;

public class User extends BaseModel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.user_id
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.user_name
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.user_birthday
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	private Date userBirthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.user_salary
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	private Double userSalary;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.user_id
	 *
	 * @return the value of t_user.user_id
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.user_id
	 *
	 * @param userId
	 *            the value for t_user.user_id
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.user_name
	 *
	 * @return the value of t_user.user_name
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.user_name
	 *
	 * @param userName
	 *            the value for t_user.user_name
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.user_birthday
	 *
	 * @return the value of t_user.user_birthday
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public Date getUserBirthday() {
		return userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.user_birthday
	 *
	 * @param userBirthday
	 *            the value for t_user.user_birthday
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public void setUserBirthday(Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.user_salary
	 *
	 * @return the value of t_user.user_salary
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public Double getUserSalary() {
		return userSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.user_salary
	 *
	 * @param userSalary
	 *            the value for t_user.user_salary
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	public void setUserSalary(Double userSalary) {
		this.userSalary = userSalary;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", userName=" + userName + ", userBirthday=" + userBirthday + ", userSalary="
				+ userSalary + "]";
	}

}