package ecloud.com.mapper.base;

import ecloud.com.base.model.BaseModel;

public interface SqlMapper<T extends BaseModel > {

	//此处的方法名必须和mapper中的映射文件中的id同名
	//回去映射文件中通过ecloud.com.mapper.base,即this.getClass().getName()+".deleteByPrimaryKey"
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	int insert(BaseModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	int insertSelective(BaseModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	T selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	int updateByPrimaryKeySelective(BaseModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 *
	 * @mbggenerated Wed Mar 22 23:36:48 CST 2017
	 */
	int updateByPrimaryKey(BaseModel record);
}
